### ISSUE TITLE
SOCI CMake Sub Project help.

### ISSUE THREAD

**Issue by amreisa** [SOCI/soci#792] opened 2020-02-27 11:41 UTC
I need Some Hellp about instruction how to use SOCI from cmake as subporject "add_subdirectory(SOCI)"
I have long time try use It but SOCI::* not work. I know this about CMake but no one try to help. And How I can do in way from SOCI CMake script Variables. How I can do that ?

**Comment by vadz** [comment] 2020-02-27 20:04
Sorry, no idea. I guess "Using library" section of `docs/installation.md` should be improved, but I don't use CMake myself, so I have no idea about what to write there.

**Comment by Leon0402** [comment] 2020-07-17 16:32
Hi there,
I guess you mean by using FetchContent? This is currently not possible and requires major changes to cmake.

https://github.com/SOCI/soci/pull/817 is an attempt to provide support for fetch content and to make using soci easier with cmake in general. It's quite a big pull request though, so I wouldn't expect it to land any time soon.

**Comment by yash101** [comment] 2020-09-03 23:03
Did you end up figuring this out?
I am searching for an easy way to link with my application, built with CMake.

I am currently using ExternalProject_Add and some execute_process'es to clone and build SOCI.
Everything was building perfectly until I tried to use the library.

I am getting an error: `#error "SOCI must be configured with C++11 support when using C++11"`

My code is being compiled with the C++17 standard, and the CMake output when SOCI's cache is generated shows CXX11 support is enabled. I have no clue how to fix this issue.

This is my first time using CMake in a project with even close to this level of complexity.

**Comment by Leon0402** [comment] 2020-09-04 06:33
Hi there, 
are you using the current master code or my branch? 

The error message certainly rings some bells, but I can't exactly remember anymore how I fixed it (or even if I fixed it or if I just was using it wrong before). Unfortunately, there wasn't anyone who was willing to review my merge request or help me with testing a few backends I simply don't have, so it's more or less abandoned until there is some more development activity here. 

What backend are you interested in? I know that my code worked perfectly fine with sqlite3 (didn't test it for external project, but I would recommend fetchContent anyway), so if that's the backend you want to use, consider checking out my pull request! ;) You might even want to help to get this merged. 

Apart from that, once I got the cmake part running it didn't take a long time to me to find some more bugs (like containers with orm custom types not working). I'm fine with contributing to a lib, even some bigger changes like the cmake pull request, but in this case I was too afraid that there will be one bug after another and I basically just spend all my time, fixing these here. So I ended up trying out some other libs.

**Comment by apappu9** [comment] 2020-09-08 01:22
Hey @yash101, if you're still getting the same error, I recently came across it and fixed it by adding the flag -DSOCI_CXX11=ON to cmake when building SOCI (more info here: http://soci.sourceforge.net/doc/release/4.0/installation/#cmake-configuration). Also could you share how you got it to work with ExternalProject_Add? I tried to follow #762, but have been struggling with it for a while. Thanks!

**Comment by yash101** [comment] 2020-09-08 01:24
@apappu9 I did use -DSOCI_CXX11=ON when I built SOCI.

I think the issue might be caused by C++ 17. Perhaps C++ 17 is too bleeding edge for SOCI.

Anyhow, for the application I am developing, I just switched to vanilla libpq 😬

**Comment by yash101** [comment] 2020-09-08 01:28
@apappu9 do you have the error message? I am trying to find which header is causing it, but I do not have a failing build anymore.

**Comment by yash101** [comment] 2020-09-08 01:36
@apappu9 I went through my commit history and I never committed when I set up ExternalProject_Add. I figured it was a dead end after seeing this issue.

Also sorry for so many replies 🥴

**Comment by yash101** [comment] 2020-09-08 01:50
Never mind, I found the code I used:

`/cmake/soci.cmake`
```cmake
macro(fetch_soci _download_module_path _download_root)
    set(SOCI_DOWNLOAD_ROOT ${_download_root})
    configure_file(
        ${_download_module_path}/soci-download.cmake
        ${_download_root}/CMakeLists.txt
        @ONLY
    )

    unset(SOCI_DOWNLOAD_ROOT)

    set(SOCI_CXX11 ON)

    execute_process(
        COMMAND "${CMAKE_COMMAND}" -G "${CMAKE_GENERATOR}" .
        WORKING_DIRECTORY ${_download_root}
    )

    execute_process(
        COMMAND "${CMAKE_COMMAND}" --build .
        WORKING_DIRECTORY ${_download_root}
    )

    add_subdirectory(
        ${_download_root}/soci-src
        ${_download_root}/soci-build
    )
endmacro()
```

`/cmake/soci-download.cmake`
```cmake
cmake_minimum_required(VERSION 3.5 FATAL_ERROR)

project(soci-download NONE)

include(ExternalProject)

ExternalProject_Add(
	soci
	SOURCE_DIR "@SOCI_DOWNLOAD_ROOT@/soci-src"
	BINARY_DIR "@SOCI_DOWNLOAD_ROOT@/src-build"
	GIT_REPOSITORY https://github.com/SOCI/soci.git
	CONFIGURE_COMMAND ""
	BUILD_COMMAND ""
	INSTALL_COMMAND ""
	TEST_COMMAND ""
)
```

I am not sure how I used these files though.
I think their usage was:

`/CMakeLists.txt`
```cmake
...

include(cmake/soci.cmake)
fetch_soci(${PROJECT_SOURCE_DIR}/cmake ${PROJECT_BINARY_DIR}/soci)
```

I pulled the library and headers path from reading the CMakeList.txt's of SOCI and figuring out what the script names it.

If you can figure out what variables those are, that would be amazing. It looks like I lost them. 

I think the error for me lies in `/cmake/soci-download.cmake`. The `-DSOCI_CXX11=ON` needs to be defined in there. I did put this definitions somewhere in one of these files, but I am not sure anymore.

Hopefully this helps. Sorry I don't have a more accurate representation of what I had done to get SOCI building as an external subproject.

**Comment by apappu9** [comment] 2020-09-08 02:04
Thank you so much!! This is really helpful 😀, I'll try it out later tonight. The error message I was getting was the same as #762 btw with the dependency target "soci" not existing (sorry for replying so late). Thanks again for spending the time to look through your old code!

**Comment by marimeireles** [comment] 2020-11-29 19:19
Hey, I'll leave my 10 cents here since I recently had some trouble with this.
To add SOCI to any project, first install SOCI. I used the following to build it from source:
`cmake -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX -G "Unix Makefiles" -DWITH_BOOST=OFF -DSOCI_CXX11=ON -DCMAKE_BUILD_TYPE=Release -DSOCI_LIBDIR=lib ..`
Then add the following to the project you wanna add SOCI to:
```
set(CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake")
find_package(Soci REQUIRED MODULE)

    target_link_libraries(${target_name} PUBLIC 
      ${SOCI_LIBRARY}
    )
```

I'm soon gonna create a conda package for SOCI and hopefully make this process a bit easier.

**Comment by kdeng00** [comment] 2021-01-11 18:12
Is anyone still having this issue? I've started using SOCI as a dependency for a project that I'm working on and I've included it as a subdirectory in my CMakeLists.txt file. I have no build issues and I can make calls to the library.

**Comment by zann1x** [comment] 2022-01-08 20:28
As @kdeng00 already stated, adding SOCI as a subdirectory in CMake works perfectly fine. \
Here is a minimal example setting it up for a SQLite3 database (assuming SOCI is in the subdirectory soci/):

CMakeLists.txt:

```cmake
cmake_minimum_required(VERSION 3.16)
project(projectname)

set(CMAKE_CXX_STANDARD 20)

option(SOCI_CXX11 "" ON)
option(WITH_SQLITE3 "" ON)
add_subdirectory(soci)

add_executable(projectname main.cpp)

# Needed so that SOCI can find the file soci/soci-config.h
target_include_directories(projectname
    PRIVATE
        ${CMAKE_BINARY_DIR}/soci/include)

target_link_libraries(projectname
    PRIVATE
        soci_core
        soci_sqlite3
)
```

main.cpp:

```cpp
#include <iostream>

#include <soci/soci.h>
#include <soci/sqlite3/soci-sqlite3.h>

int main() {
    try {
        soci::session sql(soci::sqlite3, "sample.db");
    } catch (const std::exception& e) {
        std::cerr << e.what() << std::endl;
        return EXIT_FAILURE;
    }

    return EXIT_SUCCESS;
}
```

**Comment by marimeireles** [comment] 2022-01-08 21:45
Cool!
I feel like this should be tested and added in the docs somewhere. Would be a great help for CMake beginners :)

**Closed** 2022-01-14 14:33 UTC
Labels: CMake, Documentation, Status/Need-Help

**Comment by icefoxhz** [comment] 2022-03-20 06:15
cd  soci-4.0.3
mkdir build 
cd build
cmake .. -DSOCI_CXX11=ON
