### ISSUE TITLE
ORA-00932: inconsistent datatypes: expected NUMBER got TIMESTAMP

### ISSUE THREAD

**Issue by boom0192** [SOCI/soci#253] opened 2014-05-01 23:13 UTC
First I use the create function to create the table.  Then I use the select1 function to select from the table.  When I run stmt.execute(true) it throws the exception:
ORA-00932: inconsistent datatypes: expected NUMBER got TIMESTAMP

int create(session &a_sql)
{
    try
    {
        a_sql.once << "DROP TABLE soci_t1";
    }
    catch (soci_error &exception)
    {
        // This is ok.  Oracle has no DROP TABLE IF EXISTS. 
    }
    a_sql.once << "CREATE TABLE soci_t1 (pkey VARCHAR(100) NOT NULL, vali INTEGER, vald FLOAT, valdt TIMESTAMP, PRIMARY KEY (pkey))";
}

int select1(session &a_sql)
{
    row r;
    statement stmt = (a_sql.prepare << "SELECT \* FROM soci_t1", into(r));
    stmt.execute(true);

**Comment by fluxmunki** [comment] 2019-11-07 09:21
@boom0192 I don't suppose you ever resolved this? looks like I'm hitting the same error.

**Comment by rosscsoft** [comment] 2020-01-02 14:46
This looks like a duplicate of #511 and #756 (fixed in SOCI 4.0.0).

**Comment by vadz** [comment] 2020-01-03 17:53
Thanks for testing! Closing this if it works in 4.0 -- @fluxmunki please reopen if it still doesn't.

**Closed by vadz** 2020-01-03 17:53 UTC
