### ISSUE TITLE
[C++17][BUG] Bulk operations against custom type or soci::row

### ISSUE THREAD

**Issue by kuvaldini** [SOCI/soci#901] opened 2021-07-25 20:32 UTC
In the official documentation http://soci.sourceforge.net/doc/master/statements/ paragraph "Bulk operatations" told 

  ```
    const int BATCH_SIZE = 30;
    std::vector<int> valsOut(BATCH_SIZE);
    statement st = (sql.prepare <<
                "select value from numbers",
                into(valsOut));
    st.execute();
    while (st.fetch())
    {
        std::vector<int>::iterator pos;
        for(pos = valsOut.begin(); pos != valsOut.end(); ++pos)
        {
            cout << *pos << '\n';
        }
    
        valsOut.resize(BATCH_SIZE);
    }
   ```
> Taking these points under consideration, the above code example should be treated as an idiomatic way of reading many rows by bunches of requested size.

This looks like the most optimal way to receive data from database. I consider `soci::rowset` is slower, usn't it?

Anyway, may question and request to fix the issue appeared with C++17.

**Comment by vadz** [comment] 2021-07-26 12:44
Sorry, I just don't understand at all what is the issue here. What is the problem/bug you're reporting?

**Comment by vadz** [comment] 2021-07-26 12:46
This actually looks like continuation/duplicate of #900...

**Closed by vadz** 2021-07-26 12:46 UTC

**Comment by kuvaldini** [comment] 2021-07-27 13:09
This looks like the most optimal way to receive data from database. I consider soci::rowset is slower, usn't it?

**Comment by vadz** [comment] 2021-07-27 15:12
Yes, I think this should be faster than using row-based API, but I haven't done any benchmarks. In any case, I still don't understand what is the issue/problem here? If you want to know what is faster, you need to run the benchmarks in your scenario.

**Comment by kuvaldini** [comment] 2021-07-28 07:05
@vadz  Thank you for response. It is important to be supported anyway. Even if answers are obvious. 

Have a good luck.
