### ISSUE TITLE
Code for BLOB Insert to DB2 v11.1 through SOCI

### ISSUE THREAD

**Issue by Yusuf33** [SOCI/soci#539] opened 2017-06-06 15:43 UTC
Hi,
Can anyone post a sample code cut to Insert and Fetch BLOB to a table in db2 with version 11.1 ?

The following Statement working in DB2 v10.5 but not in v11.1.
statement Stmt = (sql->prepare<<"INSERT INTO TABLE_BLOB (COL1) VALUES (BLOB(:host_variable)), use(host_variable)) ;
     where host_variable is a local variable of unsigned char and COL1 is of blob datatype.

Error that I am getting in DB2 v11.1 is ;
Statement execution error SQLMESSAGE: [IBM][CLI Driver][DB2/LINUXX8664] SQL0440N  No authorized routine named "BLOB" of type "FUNCTION" having compatible arguments was found.  SQLSTATE=42884

SOCI Version : 3.2.2
Linux : RHEL 7.3 (64 Bit)

**Comment by mloskot** [comment] 2017-09-24 22:01
The same question was asked on SO as [Code for BLOB Insert to DB2 v11.1 through SOCI](https://stackoverflow.com/q/44429396/151641) and remains unanswered.

**Comment by mloskot** [comment] 2017-09-24 22:02
The issue is unclear or report incomplete or simply there is no DB2 wizard around who would be able to tell if, perhaps the issue/incompatibility lays around client library used with SOCI.

Closing as there is no point to keep it open for long time.

**Closed by mloskot** 2017-09-24 22:02 UTC
Labels: DB2, Status/Invalid
