### ISSUE TITLE
problem compiling ODBC with TDM-GCC

### ISSUE THREAD

**Issue by mjsurette** [SOCI/soci#530] opened 2017-03-23 15:55 UTC
I am trying to compile SOCI from the latest master (commit e719c44bb89949d3c179a6390de57ccd9046878b) with TDM-GCC and get multiple unhandled case errors.  I fixed these:
[soci-cases.diff.txt](https://github.com/SOCI/soci/files/865259/soci-cases.diff.txt)

Now I get a link error:
CMakeFiles\soci_odbc.dir/objects.a -Wl,--no-whole-archive @CMakeFiles\soci_odbc.dir\linklibs.rsp
collect2.exe: error: ld returned 5 exit status

```
$ VERBOSE=1 mingw32-make.exe
"C:\Program Files\CMake\bin\cmake.exe" -HC:\Users\Mike\Documents\code\soci -BC:\Users\Mike\Documents\code\soci\build --check-build-system CMakeFiles\Makefile.cmake 0
"C:\Program Files\CMake\bin\cmake.exe" -E cmake_progress_start C:\Users\Mike\Documents\code\soci\build\CMakeFiles C:\Users\Mike\Documents\code\soci\build\CMakeFiles\progress.marks
C:/TDM-GCC-64/bin/mingw32-make -f CMakeFiles\Makefile2 all
mingw32-make[1]: Entering directory 'C:/Users/Mike/Documents/code/soci/build'
C:/TDM-GCC-64/bin/mingw32-make -f src\core\CMakeFiles\soci_core.dir\build.make src/core/CMakeFiles/soci_core.dir/depend
mingw32-make[2]: Entering directory 'C:/Users/Mike/Documents/code/soci/build'
"C:\Program Files\CMake\bin\cmake.exe" -E cmake_depends "MinGW Makefiles" C:\Users\Mike\Documents\code\soci C:\Users\Mike\Documents\code\soci\src\core C:\Users\Mike\Documents\code\soci\build C:\Users\Mike\Documents\code\soci\build\src\core C:\Users\Mike\Documents\code\soci\build\src\core\CMakeFiles\soci_core.dir\DependInfo.cmake --color=
mingw32-make[2]: Leaving directory 'C:/Users/Mike/Documents/code/soci/build'
C:/TDM-GCC-64/bin/mingw32-make -f src\core\CMakeFiles\soci_core.dir\build.make src/core/CMakeFiles/soci_core.dir/build
mingw32-make[2]: Entering directory 'C:/Users/Mike/Documents/code/soci/build'
mingw32-make[2]: Nothing to be done for 'src/core/CMakeFiles/soci_core.dir/build'.
mingw32-make[2]: Leaving directory 'C:/Users/Mike/Documents/code/soci/build'
[ 23%] Built target soci_core
C:/TDM-GCC-64/bin/mingw32-make -f src\core\CMakeFiles\soci_core_static.dir\build.make src/core/CMakeFiles/soci_core_static.dir/depend
mingw32-make[2]: Entering directory 'C:/Users/Mike/Documents/code/soci/build'
"C:\Program Files\CMake\bin\cmake.exe" -E cmake_depends "MinGW Makefiles" C:\Users\Mike\Documents\code\soci C:\Users\Mike\Documents\code\soci\src\core C:\Users\Mike\Documents\code\soci\build C:\Users\Mike\Documents\code\soci\build\src\core C:\Users\Mike\Documents\code\soci\build\src\core\CMakeFiles\soci_core_static.dir\DependInfo.cmake --color=
mingw32-make[2]: Leaving directory 'C:/Users/Mike/Documents/code/soci/build'
C:/TDM-GCC-64/bin/mingw32-make -f src\core\CMakeFiles\soci_core_static.dir\build.make src/core/CMakeFiles/soci_core_static.dir/build
mingw32-make[2]: Entering directory 'C:/Users/Mike/Documents/code/soci/build'
mingw32-make[2]: Nothing to be done for 'src/core/CMakeFiles/soci_core_static.dir/build'.
mingw32-make[2]: Leaving directory 'C:/Users/Mike/Documents/code/soci/build'
[ 47%] Built target soci_core_static
C:/TDM-GCC-64/bin/mingw32-make -f src\backends\odbc\CMakeFiles\soci_odbc.dir\build.make src/backends/odbc/CMakeFiles/soci_odbc.dir/depend
mingw32-make[2]: Entering directory 'C:/Users/Mike/Documents/code/soci/build'
"C:\Program Files\CMake\bin\cmake.exe" -E cmake_depends "MinGW Makefiles" C:\Users\Mike\Documents\code\soci C:\Users\Mike\Documents\code\soci\src\backends\odbc C:\Users\Mike\Documents\code\soci\build C:\Users\Mike\Documents\code\soci\build\src\backends\odbc C:\Users\Mike\Documents\code\soci\build\src\backends\odbc\CMakeFiles\soci_odbc.dir\DependInfo.cmake --color=
mingw32-make[2]: Leaving directory 'C:/Users/Mike/Documents/code/soci/build'
C:/TDM-GCC-64/bin/mingw32-make -f src\backends\odbc\CMakeFiles\soci_odbc.dir\build.make src/backends/odbc/CMakeFiles/soci_odbc.dir/build
mingw32-make[2]: Entering directory 'C:/Users/Mike/Documents/code/soci/build'
[ 48%] Linking CXX shared library ..\..\..\bin\libsoci_odbc_4_0.dll
cd /d C:\Users\Mike\Documents\code\soci\build\src\backends\odbc && "C:\Program Files\CMake\bin\cmake.exe" -E cmake_link_script CMakeFiles\soci_odbc.dir\link.txt --verbose=1
"C:\Program Files\CMake\bin\cmake.exe" -E remove -f CMakeFiles\soci_odbc.dir/objects.a
C:\TDM-GCC-64\bin\ar.exe cr CMakeFiles\soci_odbc.dir/objects.a @CMakeFiles\soci_odbc.dir\objects1.rsp
C:\TDM-GCC-64\bin\g++.exe    -pedantic -Werror -Wno-error=parentheses -Wall -Wpointer-arith -Wcast-align -Wcast-qual -Wfloat-equal -Wredundant-decls -Wno-long-long -std=c++11  -Wno-variadic-macros -O3 -DNDEBUG  -shared -o ..\..\..\bin\libsoci_odbc_4_0.dll -Wl,--out-implib,..\..\..\lib\libsoci_odbc_4_0.dll.a -Wl,--major-image-version,4,--minor-image-version,0 -Wl,--whole-archive CMakeFiles\soci_odbc.dir/objects.a -Wl,--no-whole-archive @CMakeFiles\soci_odbc.dir\linklibs.rsp
collect2.exe: error: ld returned 5 exit status
src\backends\odbc\CMakeFiles\soci_odbc.dir\build.make:314: recipe for target 'bin/libsoci_odbc_4_0.dll' failed
mingw32-make[2]: *** [bin/libsoci_odbc_4_0.dll] Error 1
mingw32-make[2]: *** Deleting file 'bin/libsoci_odbc_4_0.dll'
mingw32-make[2]: Leaving directory 'C:/Users/Mike/Documents/code/soci/build'
CMakeFiles\Makefile2:222: recipe for target 'src/backends/odbc/CMakeFiles/soci_odbc.dir/all' failed
mingw32-make[1]: *** [src/backends/odbc/CMakeFiles/soci_odbc.dir/all] Error 2
mingw32-make[1]: Leaving directory 'C:/Users/Mike/Documents/code/soci/build'
Makefile:126: recipe for target 'all' failed
mingw32-make: *** [all] Error 2
```

I'm using CMake 3.7.2 and TDM-GCC g++.exe (tdm64-1) 5.1.0

Please help.

Mike

**Comment by vadz** [comment] 2017-07-21 23:09
I don't see any errors here, so I have no idea what went wrong... Try executing the failing command by hand, perhaps it will give some more details. We won't be able to do anything about this without more information.

**Comment by mloskot** [comment] 2017-09-24 22:08
The issue is unclear or report incomplete. Besides, AFAIK, none of us SOCI developers use TDM-GCC.

Closing as there is no point to keep it open for long time.

**Closed by mloskot** 2017-09-24 22:08 UTC
Labels: Status/Invalid, Toolset/MinGW
