### ISSUE TITLE
Logic in get_affected_rows()

### ISSUE THREAD

**Issue by John1092** [SOCI/soci#330] opened 2015-04-24 18:12 UTC
statement.cpp
...........
else if (hasVectorUseElements_)
{
        // We already have the number of rows, no need to do anything.
        rowsAffected_ = rows_processed;
}

Not very accurate and would not work for cases like "insert into .... where not exist(select 1 from ...

In my case I just commented this out.

**Comment by mloskot** [comment] 2015-04-27 21:16
A [MCVE](http://stackoverflow.com/help/mcve) in C++ would be helpful.

**Comment by vadz** [comment] 2017-07-21 23:14
FWIW this is about the ODBC backend and it indeed won't work correctly in all cases, but then `get_affected_rows()` is just not very reliable in this backend, so I'm not sure how important is it.

**Comment by mloskot** [comment] 2017-09-24 23:56
Closing as, let's say, by design.

**Closed by mloskot** 2017-09-24 23:56 UTC
Labels: ODBC, Priority/Low
