### ISSUE TITLE
When will the next release avaliable?

### ISSUE THREAD

**Issue by yxdming** [SOCI/soci#742] opened 2019-07-22 07:42 UTC
I noticeed that the lasted version 3.2.3, which was released on Apr 9, 2015. There are so many bug s fixed from that time.
I will appreciate it so much if there is a new stable release available.
@mloskot

**Comment by mloskot** [comment] 2019-07-22 09:46
The C++ code is ready as you have noticed.
I just have no time to get the CMake stuff updated in order to provide fully-featured CMake Config-modules for SOCI and its dependencies.

A solution could be to release CMake as it is now, but packagers may come back with lots of complains  :)

**Comment by yxdming** [comment] 2019-07-22 11:36
Agree with that.
Is there any plan/schedule available now?

**Comment by mloskot** [comment] 2019-07-22 11:39
> Is there any plan/schedule available now?

No, not yet as above I've just started thinking about that idea to cut some corners. I'll see what I can achieve this week/weekend for the release.

**Comment by yxdming** [comment] 2019-07-27 15:13
Hi, @mloskot 
Did you have an evaluation about the plan of 4.0.0?
Thanks

**Comment by mloskot** [comment] 2019-07-28 21:41
No, I have not managed to do anything for this yet

**Comment by yxdming** [comment] 2019-07-29 09:49
What's a pity.
And how about 3.2.4?

**Comment by mloskot** [comment] 2019-07-29 09:57
3.x line is not maintained

**Comment by yxdming** [comment] 2019-08-06 16:45
@mloskot 
How can i help u to bring forward the progress for releasing 4.0.0. It seems there are 10 issues need to be fixed in 4.0.0.

**Comment by mloskot** [comment] 2019-08-07 12:24
@yxdming 
I don't have time to work on any outstanding issues marked for the 4.0.0 milestone.
I can only merge PRs already submitted, but there are none waiting https://github.com/SOCI/soci/pulls?q=is%3Aopen+is%3Apr+milestone%3A4.0.0

The preparation to new release takes:

1. Collect release notes and update [CHANGES](https://github.com/SOCI/soci/blob/master/CHANGES) file.
2. Bump versions in build scripts, documentation, etc.
3. Update website
4. Prepare source archive RC1, 2, ... and call for testing for a a week or two
5. Test archive locally on at least one environment.
6. Publish final release

Currently, the most time consuming part is the collection of `CHANGES` update:

1. Generate log of changes in Markdown. You fan find command in https://github.com/SOCI/soci/issues/93#issuecomment-15434667 which I used to generate this early list https://gist.github.com/mloskot/86df093cfc456c137c008bb18574dc93
2. Extract major and important changes
3. Copy them into `CHANGES` file

I contemplated and proposed automated creation of ChangeLog in https://github.com/SOCI/soci/commit/2ab0fb90120440243e0e1528bb1d16dbe71928ba  but I don't think there is general agreement about it as some folks prefer the distilled `CHANGES` file.
However, there is nothing wrong with including the `CHANGELOG.md` as raw extract from GitHub generated by the commands pointed above.

If you'd like to give the `CHANGES` preparation a try, you are welcome.
Otherwise, I will try to book some time in next 2-3 days to get it done.
Then, we should be pretty much ready for release.

**Comment by ahmedyarub** [comment] 2019-08-31 00:35
I'll be taking care of these in my free time. I just hope that you would be merging the PR'S :)

**Comment by mloskot** [comment] 2019-09-20 16:13
FYI, I have just completed collecting the list of [CHANGES](https://github.com/SOCI/soci/blob/d769e5f923c4ae0dd59db08718d77dbebd8993f7/CHANGES) up to now.

**Comment by mloskot** [comment] 2019-09-20 16:14
Closing this as duplicate of #616

**Closed by mloskot** 2019-09-20 16:14 UTC
Labels: Category/Question

**Comment by mloskot** [comment] 2019-10-25 22:45
I have just published SOCI 4.0.0 RC1 calling for tests

https://sourceforge.net/p/soci/mailman/message/36793193/

I'm expecting final release in a week or so, depending on stream of RC issues reported back.

**Comment by mloskot** [comment] 2019-11-09 20:12
[SOCI 4.0.0 has been released](https://sourceforge.net/p/soci/mailman/message/36804750/)

Please, prefer to use the mailing lists for questions.
