### ISSUE TITLE
oracle datatype TIMESTAMP error

### ISSUE THREAD

**Issue by babyaaaaaa** [SOCI/soci#756] opened 2019-09-29 04:34 UTC
hi,  i use this code to select from oracle :
soci::rowset<<soci::row>> rs = (query.prepare << "select * from xxxx");

if the table xxxx has the datatype: TIMESTAMP then it will has an error:
 err:ORA-00932: inconsistent datatypes: expected NUMBER got TIMESTAM
how could I use the select *

**Comment by rosscsoft** [comment] 2020-01-02 14:39
I have seen this one myself in SOCI 3.2.3 and I believe this is a duplicate of #511 which was fixed in SOCI 4.0.0.

If the first column of the select statement is a TIMESTAMP, you will likely see the error "db column type -858993460 not supported for dynamic selects" (where -858993460 can be any number).  

If the column preceding the TIMESTAMP is a NUMBER type, you will see the error "ORA-00932: inconsistent datatypes: expected NUMBER got TIMESTAMP".

Note that the fix for #511 will allow the use of TIMESTAMP columns in a soci::row but will bind as a string so you cannot use row.get<std::tm>().  You will need to parse the TIMESTAMP value out of a string.

You can use std::tm with TIMESTAMP columns if you avoid dynamic binding (soci::row/soci::rowset) and just use a std::tm with soci::into(). If you need to iterate records, you can use statement::fetch().  Obviously, you will need to know in advance which columns your "select * from ..." will return.

Since std::tm only supports 1 second accuracy, you will lose the sub-second accuracy of TIMESTAMP.

**Comment by rosscsoft** [comment] 2020-01-02 14:43
Also looks like #253

**Comment by vadz** [comment] 2020-01-03 17:52
@rosscsoft So do I understand it correctly that even with 4.0 using `TIMESTAMP` in a `row` doesn't really work, as it doesn't have the right type? If so, this one should probably be left open with the updated description...

**Comment by vadz** [comment] 2020-01-03 17:56
Sorry, I was too hasty and didn't notice that you opened #777 for this issue. I think this one can be closed as the part which remains not fixed is exactly what #777 is about.

Thanks for looking at this!

**Closed by vadz** 2020-01-03 17:56 UTC
Labels: Oracle
