### ISSUE TITLE
Statement binding & variable scope

### ISSUE THREAD

**Issue by mattj0nes2** [SOCI/soci#467] opened 2016-05-04 17:03 UTC
Say I have the following loop, where `i` is obviously a temp variable:

```
statement stmnt(db);

for(int i = 1; i < 4; i++)
{
    stmnt.exchange(use(i));
}

stmnt.define_and_bind();
```

When I later call `stmnt.define_and_bind()` only the last instance of `i` is used, so I end up preparing a statement where the value 4 (`i` post-incremented) is bound 3 times.

Given the style of the SOCI API I can kind of understand why this is, but what would be the best practice workaround? I'd love the answer to be "Hey, you can bind by value, just do ...", but I'm guessing not.

Obviously the above example is contrived, it might more likely be that I'm calling a function several times with different inputs and want to use the result each time as part of the statement.

The only workaround that comes to mind is to store the results first in a vector, then traverse over that, e.g:

```
statement stmnt(db);

std::vector<int> temp;

for(int i = 1; i < 4; i++)
{
    temp.push_back(i);
}

for(std::vector<int>::const_iterator it = temp.begin(); it != temp.end(); it++)
{
    stmnt.exchange(use(*it));
}

stmnt.define_and_bind();
```

This has the desired effect, but at the cost of additional memory and repeating what could in the real world be a very long loop.

You could try and capture some reference to the values as they're added to the vector in the `for` loop, thus negating the need for the later iterater loop, but you've generally no guarantee with these types of containers that the address you capture will remain valid as further elements are added.

So how do you tend to approach this with SOCI? I think it's generally a great API but this feels like a bit of a shortcoming. I'm trying to port a few projects to SOCI (well, I already have, but they weren't previously using prepared statements so now I'm trying to change that too) and this feels like an ugly hack to have to add to existing code.

Any help greatly appreciated,
Matt

**Comment by msobczak** [comment] 2016-05-04 19:58
On 04/05/2016 19:03, mattj0nes2 wrote:

> When I later call |stmnt.define_and_bind()| only the last instance of
> |i| is used, so I end up preparing a statement where the value 4 (|i|
> post-incremented) is bound 3 times.

It is worse than that. Formally, the variable i no longer exists (it is 
local to the loop scope) at the point of statement execution, so you get 
the undefined behavior when the statement refers to the dangling 
reference or pointer.

> Given the style of the SOCI API I can kind of understand why this is,
> but what would be the best practice workaround?

Workaround to what goal, exactly? You have shown a code example that 
tries to solve some problem, but we do not know what that problem is.

> The only workaround that comes to mind is to store the results first in
> a vector, then traverse over that, e.g:

It need not be a vector. Any other way of retaining objects around is 
OK, and for reasons that you have noted, list might be a better choice.

> This has the desired effect, but at the cost of additional memory and
> repeating what could in the real world be a very long loop.

No, in the real world it will not be a very long loop, unless you have 
an SQL query with a very large number of unbound parameters (and in the 
real world you do not).

> You could try and capture some reference to the values as they're added
> to the vector in the |for| loop, thus negating the need for the later
> iterater loop, but you've generally no guarantee with these types of
> containers that the address you capture will remain valid as further
> elements are added.

That's why list might be better.

> So how do you tend to approach this with SOCI?

Approach what, exactly? What do you try to achieve?

> great API but this feels like a bit of a shortcoming. I'm trying to port
> a few projects to SOCI

And what is the SQL query in that particular case? Does it have a 
constant or a variable number of parameters? How many are they?

Regards,

-- 
Maciej Sobczak * www.msobczak.com * www.inspirel.com

**Comment by mattj0nes2** [comment] 2016-05-05 17:33
There are two problems I've come up against. Not that I wouldn't necessarily have encountered the same or similar issues with another API, it's just I thought it worth asking in case there are options or workarounds I wasn't aware of. I guess it's really more "Can we have a bind by value option, please?"

The first issue, and the reason for the initial post, was that I had a large number of parameters to pass and it felt a shame to have to buffer them all, something the likes of:
```
std::ostringstream ssQuery;
int i = 0;

ssQuery << "SELECT a FROM b WHERE c IN (0";

while((i = func()) != -1)
{
	ssQuery << ",:x";

	stmnt.exchange(use(i));
}
```
As we've said you can of course store things locally for use later, it'd just be nice if the option was there of the API handling this centrally so you didn't have to create local storage wherever a similar situation arises.

The second, slightly more awkward problem I've come across where bind by value would be a god send, is where more than one function shares responsibility for building up the query. Something like:

``` 
void TopLevelFunc()
{
	std::ostringstream ssQuery;

	statement stmnt(db);

	ssQuery << "SELECT a FROM b ";

	BuildWhereClause(ssQuery, stmnt);

	stmnt.define_and_bind();
}

void BuildWhereClause(std::ostringstream &ssQuery, statement &stmnt)
{
	int i = 0;
	std::string j;

	ssQuery << "WHERE c IN (0, ";

	while((i = intFunc()) != -1)
	{
		ssQuery << ",:x";
	
		stmnt.exchange(use(i));
	}

	ssQuery << "AND d IN ("string", "

	while((j = stringFunc()) != "")
	{
		ssQuery << ",:x";
	
		stmnt.exchange(use(j));
	}

	ssQuery << ")";
}
```

Again, you could allocate storage and have `TopLevelFunc` pass int and string lists by reference to `BuildWhereClause`, but that requires `TopLevelFunc` to know in advance what argument types `BuildWhereClause`  will bind. With bind by value the statement could be reasily passed to other functions to be executed later.

Don't forget I'm porting both to SOCI/postgres (from Firebird, which I'll never use again) and attempting to convert code that simply builds unchecked strings at present to the relative safety of prepared statements, so anything that would make this process easier is very much at the front of my mind ...

It's not that I expect bind by value to be made available any time soon, if ever, and maybe I shouldn't have bothered posting, but if you don't ask ... I understand it might not be a walk in the park to implement, but it'd be a stand out feature.

Thanks for your time anyway.

**Comment by mloskot** [comment] 2017-09-24 23:55
Since there have been no more feedback, can we close this as *by design*? 

Unless @msobczak you want to keep the idea on  backburner, do you?

**Comment by mloskot** [comment] 2017-09-25 00:10
Related issue with binding https://github.com/SOCI/soci/issues/562#issuecomment-317511977

**Comment by mloskot** [comment] 2017-09-26 23:29
Closing

**Closed** 2017-09-26 23:30 UTC
Labels: Category/Question, Core
